//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comquiz.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("comquiz.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Load from file.
        /// </summary>
        public static string mainMenu_chooseFileButtonLabel {
            get {
                return ResourceManager.GetString("mainMenu_chooseFileButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select a QUIZ file.
        /// </summary>
        public static string mainMenu_chooseFileDialogTitle {
            get {
                return ResourceManager.GetString("mainMenu_chooseFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Start quiz.
        /// </summary>
        public static string mainMenu_displayQuizScreen {
            get {
                return ResourceManager.GetString("mainMenu_displayQuizScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Number of questions: .
        /// </summary>
        public static string mainMenu_questionsNumber {
            get {
                return ResourceManager.GetString("mainMenu_questionsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Loaded quiz:.
        /// </summary>
        public static string mainMenu_quizLoadedLabel {
            get {
                return ResourceManager.GetString("mainMenu_quizLoadedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error while reading QUIZ file.
        /// </summary>
        public static string mainMenu_quizParsingErrorString {
            get {
                return ResourceManager.GetString("mainMenu_quizParsingErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Quiz part:.
        /// </summary>
        public static string mainMenu_quizPart {
            get {
                return ResourceManager.GetString("mainMenu_quizPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ENTIRE.
        /// </summary>
        public static string mainMenu_quizPart_Entire {
            get {
                return ResourceManager.GetString("mainMenu_quizPart_Entire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a HALF.
        /// </summary>
        public static string mainMenu_quizPart_Half {
            get {
                return ResourceManager.GetString("mainMenu_quizPart_Half", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 5th part.
        /// </summary>
        public static string mainMenu_quizPartial_Fifth {
            get {
                return ResourceManager.GetString("mainMenu_quizPartial_Fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 1st part.
        /// </summary>
        public static string mainMenu_quizPartial_First {
            get {
                return ResourceManager.GetString("mainMenu_quizPartial_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 4th part.
        /// </summary>
        public static string mainMenu_quizPartial_Forth {
            get {
                return ResourceManager.GetString("mainMenu_quizPartial_Forth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 2nd part.
        /// </summary>
        public static string mainMenu_quizPartial_Second {
            get {
                return ResourceManager.GetString("mainMenu_quizPartial_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 6th part.
        /// </summary>
        public static string mainMenu_quizPartial_Sixth {
            get {
                return ResourceManager.GetString("mainMenu_quizPartial_Sixth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 3rd part.
        /// </summary>
        public static string mainMenu_quizPartial_Third {
            get {
                return ResourceManager.GetString("mainMenu_quizPartial_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Randomize answers order.
        /// </summary>
        public static string mainMenu_randomizeAnswers_Label {
            get {
                return ResourceManager.GetString("mainMenu_randomizeAnswers_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove list annotations from the response text (e.g. 1) o 2) oppure A. o B. ) and randomize the order in which they are displayed..
        /// </summary>
        public static string mainMenu_randomizeAnswers_Tooltip {
            get {
                return ResourceManager.GetString("mainMenu_randomizeAnswers_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Randomize questions order.
        /// </summary>
        public static string mainMenu_randomizeQuestions_Label {
            get {
                return ResourceManager.GetString("mainMenu_randomizeQuestions_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Take the selected set of questions and randomize the order in which they are displayed.
        /// </summary>
        public static string mainMenu_randomizeQuestions_Tooltip {
            get {
                return ResourceManager.GetString("mainMenu_randomizeQuestions_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select options:.
        /// </summary>
        public static string mainMenu_selectOptions {
            get {
                return ResourceManager.GetString("mainMenu_selectOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a To start, select a QUIZ file.
        /// </summary>
        public static string mainMenu_toStartMessage {
            get {
                return ResourceManager.GetString("mainMenu_toStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a End quiz.
        /// </summary>
        public static string quizScreen_endQuiz {
            get {
                return ResourceManager.GetString("quizScreen_endQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Next question.
        /// </summary>
        public static string quizScreen_nextQuestionLabel {
            get {
                return ResourceManager.GetString("quizScreen_nextQuestionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You selected fewer answers than you should. Pick another answer from the list..
        /// </summary>
        public static string quizScreen_notEnoughSelectedAnswers {
            get {
                return ResourceManager.GetString("quizScreen_notEnoughSelectedAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Question .
        /// </summary>
        public static string quizScreen_questionCounter_1 {
            get {
                return ResourceManager.GetString("quizScreen_questionCounter_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  of .
        /// </summary>
        public static string quizScreen_questionCounter_2 {
            get {
                return ResourceManager.GetString("quizScreen_questionCounter_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a QUIZ completed. Result.
        /// </summary>
        public static string quizScreen_quizCompleted_1 {
            get {
                return ResourceManager.GetString("quizScreen_quizCompleted_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Right questions.
        /// </summary>
        public static string quizScreen_quizCompleted_2 {
            get {
                return ResourceManager.GetString("quizScreen_quizCompleted_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a out of a total of.
        /// </summary>
        public static string quizScreen_quizCompleted_3 {
            get {
                return ResourceManager.GetString("quizScreen_quizCompleted_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Right answers for this question:.
        /// </summary>
        public static string quizScreen_rightAnswersCounter {
            get {
                return ResourceManager.GetString("quizScreen_rightAnswersCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Show answers.
        /// </summary>
        public static string quizScreen_showRightAnswersLabel {
            get {
                return ResourceManager.GetString("quizScreen_showRightAnswersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The QUIZ seems to contain a question with no text or answer (?????).
        /// </summary>
        public static string quizSheet_parsingError_badOrInvalidQuestion_1 {
            get {
                return ResourceManager.GetString("quizSheet_parsingError_badOrInvalidQuestion_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The QUIZ seems to contain a question without question or without answers (?????).
        /// </summary>
        public static string quizSheet_parsingError_badOrInvalidQuestion_2 {
            get {
                return ResourceManager.GetString("quizSheet_parsingError_badOrInvalidQuestion_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Loaded file does not appear to be a quiz!.
        /// </summary>
        public static string quizSheet_parsingError_fileIsNotQuiz {
            get {
                return ResourceManager.GetString("quizSheet_parsingError_fileIsNotQuiz", resourceCulture);
            }
        }
    }
}
